DATA_TRAIN_CSV_PATH = "/data/luiz/dataset/partitions/species-classifier/nacti/train.csv"
DATA_VAL_CSV_PATH = "/data/luiz/dataset/partitions/species-classifier/nacti/val.csv"
DATA_TEST_CSV_PATH = "/data/luiz/dataset/partitions/species-classifier/nacti/test.csv"
MODEL = "ImprovedAIPResNet50"
OUTPUT_DIR = "/data/luiz/dataset/EcoAIP/nacti"
PATIENCE = 15
NUM_CLASS = 10
TRAIN_SIZE = 1200
BATCH_SIZE = 16
EPOCHS = 100
TASK = "species-classifier"
LEARNING_RATE_MODEL = 1e-4
IMAGE_SIZE = (400, 400)
SEED = 42
