DATA_TRAIN_CSV_PATH = "/data/luiz/dataset/partitions/detection-classifier/wcs/train.csv"
DATA_VAL_CSV_PATH = "/data/luiz/dataset/partitions/detection-classifier/wcs/val.csv"
DATA_TEST_CSV_PATH = "/data/luiz/dataset/partitions/detection-classifier/wcs/test.csv"
MODEL = "Yolov11"
OUTPUT_DIR = "/data/luiz/dataset/EcoAIP/wcs"
PATIENCE = 20
NUM_CLASS = 1
TRAIN_SIZE = 10
VAL_SIZE = 6
TEST_SIZE = 10
BATCH_SIZE = 4
BBOX_IS_NORMALIZED = False
EPOCHS = 150
TASK = "detection-classifier"
LEARNING_RATE_MODEL = 1e-2
IMAGE_SIZE = (640, 640)
SEED = 42
# DATA_TRAIN_CSV_PATH = "/data/luiz/dataset/partitions/detection-classifier/wcs/train.csv"
# DATA_VAL_CSV_PATH = "/data/luiz/dataset/partitions/detection-classifier/wcs/val.csv"
# DATA_TEST_CSV_PATH = "/data/luiz/dataset/partitions/detection-classifier/wcs/test.csv"
# MODEL = "Yolov11"
# OUTPUT_DIR = "/data/luiz/dataset/EcoAIP/wcs"
# PATIENCE = 20
# NUM_CLASS = 1
# TRAIN_SIZE = 10
# VAL_SIZE = 60
# TEST_SIZE = 10
# BATCH_SIZE = 16
# BBOX_IS_NORMALIZED = False
# AUGMENT_IMAGE = True
# EPOCHS = 150
# TASK = "detection-classifier"
# LEARNING_RATE_MODEL = 1e-2
# IMAGE_SIZE = (640, 640)
# SEED = 42
