DATA_TRAIN_CSV_PATH = "/data/luiz/dataset/partitions/animal-classifier/nacti/train.csv"
DATA_VAL_CSV_PATH = "/data/luiz/dataset/partitions/animal-classifier/nacti/val.csv"
DATA_TEST_CSV_PATH = "/data/luiz/dataset/partitions/animal-classifier/nacti/test.csv"
MODEL = "AIPResNet50"
OUTPUT_DIR = "/data/luiz/dataset/EcoAIP/nacti"
PATIENCE = 8
NUM_CLASS = 2
TRAIN_SIZE = 9600
BATCH_SIZE = 16
EPOCHS = 40
TASK = "animal-classifier"
LEARNING_RATE_MODEL = 1e-4
IMAGE_SIZE = (224, 224)
SEED = 42
