DATA_TRAIN_CSV_PATH = "/data/luiz/dataset/partitions/animal-classifier/wcs/train.csv"
DATA_VAL_CSV_PATH = "/data/luiz/dataset/partitions/animal-classifier/wcs/val.csv"
DATA_TEST_CSV_PATH = "/data/luiz/dataset/partitions/animal-classifier/wcs/test.csv"
MODEL_NAME = "normal"
MODEL = "AIPResNet50"
OUTPUT_DIR = "/data/luiz/dataset/EcoAIP/wcs"
PATIENCE = 20
TRAIN_SIZE = 4800
BATCH_SIZE = 16
EPOCHS = 100
LEARNING_RATE_MODEL = 0.001
IMAGE_SIZE = (300, 300)
SEED = 42
