DATA_TRAIN_CSV_PATH = "/data/luiz/dataset/partitions/species-classifier/wcs/train.csv"
DATA_VAL_CSV_PATH = "/data/luiz/dataset/partitions/species-classifier/wcs/val.csv"
DATA_TEST_CSV_PATH = "/data/luiz/dataset/partitions/species-classifier/wcs/test.csv"
MODEL = "ResNet50"
MODEL_NAME = "normal"
OUTPUT_DIR = "/data/luiz/dataset/EcoAIP/wcs"
PATIENCE = 15
NUM_CLASS = 10
TRAIN_SIZE = 2400
BATCH_SIZE = 16
AUGMENT_IMAGE = True
EPOCHS = 100
TASK = "species-classifier"
LEARNING_RATE_MODEL = 1e-4
IMAGE_SIZE = (400, 400)
SEED = 42
