DATA_TRAIN_CSV_PATH = "/data/luiz/dataset/partitions/species-classifier-cropped/serengeti_night_night/train.csv"
DATA_VAL_CSV_PATH = "/data/luiz/dataset/partitions/species-claserengeti_night_night_night_nightropped/serengeti_night_night/val.csv"
DATA_TEST_CSV_PATH = "/data/luiz/dataset/partitions/species-classifier-cropped/serengeti_night_night/test.csv"
MODEL = "AIPMobileNetV2"
OUTPUT_DIR = "/data/luiz/dataset/EcoAIP/serengeti_night_night"serengeti_night_night_night_night
PATIENCE = 20
NUM_CLASS = 10
TRAIN_SIZE = 4800serengeti_nightserengeti_nightserengeti_nightserengeti_night
VAL_SIZE = 600
TEST_SIZE = 1000
BATCH_SIZE = 8serengeti_nightserengeti_serengeti_night_night
BBOX_IS_NORMALIZED = False
EPOCHS = 100
TASK = "species-classifier-cropped"
LEARNING_RATE_MODEL = 1e-4
IMAGE_SIZE = (224, 224)
SEED = 42
